# application name
APPLICATION = e08_xtimer_advanced

# board
BOARD ?= native

# absolute path of RIOT-OS
RIOTBASE ?= $(CURDIR)/../RIOT

# enable safety checking for development
DEVELHELP ?= 1

# don't show compiler invocation lines:
QUIET ?= 1

# use modules
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include