# application name
APPLICATION = e07_thread_ipc

# board
BOARD ?= native

# absolute path of RIOT-OS
RIOTBASE ?= $(CURDIR)/../RIOT

# enable safety checking for development
DEVELHELP ?= 1

# don't show compiler invocation lines:
QUIET ?= 1

# use modules
USEMODULE += shell
USEMODULE += shell_commands

include $(RIOTBASE)/Makefile.include