# application name
APPLICATION = e05_hts221_sensor

# board
BOARD ?= native

# absolute path of RIOT-OS
RIOTBASE ?= $(CURDIR)/../RIOT

# modules used
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += hts221

include $(RIOTBASE)/Makefile.include