# application name
APPLICATION = e06_thread_concurrency

# board
BOARD ?= native

# absolute path of RIOT-OS
RIOTBASE ?= $(CURDIR)/../RIOT

# enable safety checking for development
DEVELHELP ?= 1

# don't show compiler invocation lines:
QUIET ?= 1

# use xtimer module
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include